"use client";
import { useRef, useState } from "react";

type Props = {
  highlightedHtml: string;
  language?: string;
};

export default function CodeBlock({ highlightedHtml, language }: Props) {
  const ref = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (!ref.current) return;
    const code = ref.current.querySelector("code")?.innerText ?? "";
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative group" ref={ref}>
      {/* HTML is safe — generated by Shiki on the server, not from user input */}
      <div dangerouslySetInnerHTML={{ __html: highlightedHtml }} />
      <div className="absolute top-2 right-2 flex items-center gap-2">
        {language && <span className="text-xs text-slate-400">{language}</span>}
        <button
          onClick={handleCopy}
          className="opacity-0 group-hover:opacity-100 text-xs px-2 py-1 rounded bg-slate-700 text-white transition-opacity"
        >
          {copied ? "✓ Copied" : "Copy"}
        </button>
      </div>
    </div>
  );
}
